### ISSUE TITLE
Find latest run with all timesteps

### ISSUE THREAD

**Issue by guidocioni** [ecmwf/ecmwf-opendata#13]
I know that the `latest()` function returns the latest run for a specific setting, but this consider all runs, also those that stil don't have all files online.
Is there a way to find the latest complete run with all steps present on the server?
I tried to specify `step` in the request but that didn't work.

**Comment by packman2008** [comment]
The following code could be simplified but I've left it in this state because (I think) it shows better how it works...

`#!/usr/bin/python3

import re
from datetime import datetime
from ecmwf.opendata import Client

client = Client(source="ecmwf")

format = '%Y%m%d%H'

latest_90_run = client.latest(
    type="fc",
    step=90,
    param=["2t"],
)

latest_90_date = latest_90_run.strftime(format)

latest_144_run = client.latest(
    type="fc",
    step=144,
    param=["2t"],
)

latest_144_date = latest_144_run.strftime(format)

if (latest_144_date == latest_90_date):
    print(latest_144_date)
else:
    print(latest_90_date)
`
Issue  #11 reports a fault with the client.latest function where it errors when the 18z run is the last run. The code above fors for runs 00z, 06z and 12z at the moment.

**Comment by guidocioni** [comment]
Yep, that's what I also experienced.
For the moment I'm relying on a bash script to get the latest run, I think it should be fine for now.
